### ISSUE TITLE
scdetect-cc for Dummies -- ex-03 -- typo for "Raw continuous waveform data"

### ISSUE THREAD

**Issue by funkes** [swiss-seismological-service/scdetect#122]
Playing with the famous documentation [1] probably I've found a typo:

Below the heading "Raw continuous waveform data" related to example ex-03 the preparation for the wget-call starts with an "echo"-sequence with the url to fdsnws. In the docu I've found:

"http://eida.ethz.ch/fdsnws/dataselect/query"

For me it works with an additional "/1/":

"http://eida.ethz.ch/fdsnws/dataselect/1/query"

Thanks for the great software and the useful documentation!

---
[1] https://scdetect.readthedocs.io/en/stable/base/SCDetect-for-Dummies.html#offline-playback

**Comment by damb** [comment]
Thanks for pointing this out. Of course, that's a valid point. Please, don't hesitate to provide a PR.

The documentation sources are available in the [`doc/base/`](https://github.com/swiss-seismological-service/scdetect/blob/8fb93fefff6dca7091511926e4df1be858d354e4/doc/base/) directory (relative to the repository's root directory). In your case the file [`Offline-Playback.rst`](https://github.com/swiss-seismological-service/scdetect/blob/8fb93fefff6dca7091511926e4df1be858d354e4/doc/base/Offline-Playback.rst) requires a patch. Once a new release is tagged RTD generates a new version of the documentation and the fix should be public. Also, if you need any further help, please let me know.
