### ISSUE TITLE
typo in scdetect-cc for Dummies -- screen results --record-url?

### ISSUE THREAD

**Issue by funkes** [swiss-seismological-service/scdetect#123]
To show seismograms by scolv (topic scdetect-cc for Dummies -- Offline Playback -- examples ex-02 & ex-03 -- screen results) I changed the option "--record-url" of scolv from

"fdsnws://eida-federator.ethz.ch/fdsnws/dataselect/1/query"

to

"fdsnws://eida.ethz.ch".

Probably the very useful documentation [1] contains a typo?

---

[1] https://scdetect.readthedocs.io/en/stable/base/SCDetect-for-Dummies.html#offline-playback

**Comment by damb** [comment]
Thanks for reporting.

Technically, the [`eidaws-federator`](http://eida-federator.ethz.ch/) URL should work, as well. The required MSEED data shouldn't have restricted access permissions and therefore should be accessible.

Though, for the sake of consistency we may switch to ETHZ's `fdsnws-dataselect` endpoint URL. @mmesim, any strong opinions against switching?

**Comment by mmesim** [comment]
> Though, for the sake of consistency we may switch to ETHZ's `fdsnws-dataselect` endpoint URL. @mmesim, any strong opinions against switching?

No, please go ahead. 
Thanks @funkes for reporting.

**Comment by damb** [comment]
@funkes, could you please provide a PR? Thanks.

**Comment by funkes** [comment]
See branch "patch-1"; hopefully it meets your suggestions?!

Sorry for my hesitance, but it was my first PR on GIT. So I'm not sure, whether I've found a proper way.

Are explicite hints to the related issues (#122, #123) useful?
