### ISSUE TITLE
Add detection result summary for offline playback tutorial examples

### ISSUE THREAD

**Issue by damb** [swiss-seismological-service/scdetect#128]
The template configuration of the [third offline playback example](https://scdetect.readthedocs.io/en/stable/base/SCDetect-for-Dummies.html#example-multi-detector-multi-station-multi-channel-detection) ([sources](https://github.com/swiss-seismological-service/scdetect/blob/3372889183d995f408a601245ba910ac4c8b079d/doc/base/Offline-Playback.rst)) contains overall three detector configurations. Though, when following the tutorial and running `scdetect-cc` there are no detections for the detector with `"detectorId"` `"detector-03"`. Is this on purpose, @mmesim?

**Comment by mmesim** [comment]
> Is this on purpose, @mmesim?

No. I did not notice that.

**Comment by damb** [comment]
Technically, it is fine if there is no detection. Usually, users don't know ahead of time whether there are detections for a specific template or not.

Anyway, providing the expected results (e.g. a table including the detection origin times and the detector identifiers) as part of the tutorial would IMO be of great value.
